---
language: ruby
sudo: false
addons:
  apt:
    sources:
    - augeas
    packages:
    - libaugeas-dev
    - libxml2-dev
    - libgmp3-dev
bundler_args: "--without development --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}"
cache: bundler
script: bundle exec rake test
before_install:
 - 'bundler --version || gem install bundler' # TODO:Remove if fixed - travis-ci/travis-ci#5578
 - 'rm -f Gemfile.lock'
matrix:
  fast_finish: true
  include:
  - rvm: '2.1'
    env: PUPPET_VERSION="~> 3.0"
  - rvm: '2.1'
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES=yes
  - rvm: '2.1'
    sudo: required
    services: docker
    env: PUPPET_VERSION="3.8.7" RS_SET="centos-6-x86_64-docker"
    script: bundle exec rake acceptance
  - rvm: '2.1'
    sudo: required
    services: docker
    env: PUPPET_VERSION="3.8.7" RS_SET="debian-7-x86_64-docker"
    script: bundle exec rake acceptance
  - rvm: '2.1'
    sudo: required
    services: docker
    env: PUPPET_VERSION="3.8.7" RS_SET="ubuntu-14.04-x86_64-docker"
    script: bundle exec rake acceptance
  - rvm: '2.1.8'
    env: PUPPET_VERSION="~> 4.0"
  - rvm: '2.1.8'
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES=yes
  # FIXME: GH Issue #3 - Activate acceptance tests on Travis CI for Puppet Enterprise, at least 2.8.8 and 3.8.2
notifications:
  email: false
  slack:
    rooms:
      secure: jKciSvj0RpuEcUSuEG4jXTsfWKo3sN1eYzdy9fdeO6ku7PCVkbLWunfrED7zEHGbfiiiAkdUoMqrgxQIz+iyEmS/kusa3/3II4J4NYcQE3jJz4+57ovfoMEJY1NWGofohW06NHkg+c9VwPKdtdUDWEcJ9jVvntXcPlMyJkoSk7I+EWyonyR/hzhDn8EjYGA+PQ+xdFAvBr1hN+1AFUGVwOub91Kv5UGjT6A/kqKx0uNUqF1raiizmpx2AZDixGnDRv2RpDDKjdUjA34RIHXxTrJvP4GIDInEho9Cnt11/OJtk7xm65wBS7vA3eCKse/QoPmbTpO21+HG0/pwKDujZL9mcbCGofRpfTtrDS5Fd0y3VxC3iyJN3fOUP9hxk3u+SZDWXFQAFVoR12LI9FMNSV5p4Kb0HoZ+6y7rk72ET0a76ubHu+r04pH14g8JTWi2ILI4DTvXOixmNZZIYbk8iodLUcxoubyIDcKkvaJ1MjXlEF3ZVg3+HYtk42xyir6uSKjA9OTHuHJkmxzSkjLaGh5SayhTTCf9FKiPcjztM2dHyZ18F0ZwCWAqmiMtSgKS9NkIBL1xJJWa8NAo8q5XOi1dlGUqLrQIxuA0aRoICxHjXF31hg7qRzzCZMM0MptNbkNxtxFtzg1n9tGQyepJBZyWJxvvk31N1sLHhdxFrDQ=
    on_success: always
    on_failure: always
    on_start: always
