---
language: ruby
sudo: false
addons:
  apt:
    sources:
    - augeas
    packages:
    - libaugeas-dev
    - libxml2-dev
    - libgmp3-dev
bundler_args: "--without development --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}"
cache: bundler
script: bundle exec rake test
before_install:
 - 'bundler --version || gem install bundler'
matrix:
  fast_finish: true
  include:
  - rvm: '1.8'
    env: PUPPET_GEM_VERSION="~> 2.7.0" FACTER_GEM_VERSION="~> 1.6.0"
    gemfile: gemfiles/Gemfile18.facter16
  - rvm: '1.8'
    env: PUPPET_GEM_VERSION="~> 2.7.0" FACTER_GEM_VERSION="~> 1.7.0"
    gemfile: gemfiles/Gemfile18.facter17
  - rvm: '1.9'
    env: PUPPET_GEM_VERSION="~> 3.0"
    gemfile: gemfiles/Gemfile19
  - rvm: '2.0'
    env: PUPPET_GEM_VERSION="~> 3.0"
    gemfile: gemfiles/Gemfile20
  - rvm: '2.1'
    env: PUPPET_GEM_VERSION="~> 3.0"
    before_script:
     - 'mkdir -p ./.tmp'
     - 'curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./.tmp/cc'
     - 'chmod +x ./.tmp/cc'
     - './.tmp/cc before-build'
    after_script: './.tmp/cc after-build --exit-code $TRAVIS_TEST_RESULT'
  # TODO: Restore after fixing https://github.com/coi-gov-pl/puppet-jboss/issues/98
  # - rvm: '2.1'
  #   env: PUPPET_GEM_VERSION="~> 3.0" STRICT_VARIABLES=yes
  # FIXME: GH Issue #3 - Activate acceptance tests on Travis CI for Puppet Enterprise, at least 2.8.8 and 3.8.2
notifications:
  email: false
  slack:
    rooms:
      secure: jKciSvj0RpuEcUSuEG4jXTsfWKo3sN1eYzdy9fdeO6ku7PCVkbLWunfrED7zEHGbfiiiAkdUoMqrgxQIz+iyEmS/kusa3/3II4J4NYcQE3jJz4+57ovfoMEJY1NWGofohW06NHkg+c9VwPKdtdUDWEcJ9jVvntXcPlMyJkoSk7I+EWyonyR/hzhDn8EjYGA+PQ+xdFAvBr1hN+1AFUGVwOub91Kv5UGjT6A/kqKx0uNUqF1raiizmpx2AZDixGnDRv2RpDDKjdUjA34RIHXxTrJvP4GIDInEho9Cnt11/OJtk7xm65wBS7vA3eCKse/QoPmbTpO21+HG0/pwKDujZL9mcbCGofRpfTtrDS5Fd0y3VxC3iyJN3fOUP9hxk3u+SZDWXFQAFVoR12LI9FMNSV5p4Kb0HoZ+6y7rk72ET0a76ubHu+r04pH14g8JTWi2ILI4DTvXOixmNZZIYbk8iodLUcxoubyIDcKkvaJ1MjXlEF3ZVg3+HYtk42xyir6uSKjA9OTHuHJkmxzSkjLaGh5SayhTTCf9FKiPcjztM2dHyZ18F0ZwCWAqmiMtSgKS9NkIBL1xJJWa8NAo8q5XOi1dlGUqLrQIxuA0aRoICxHjXF31hg7qRzzCZMM0MptNbkNxtxFtzg1n9tGQyepJBZyWJxvvk31N1sLHhdxFrDQ=
    on_success: always
    on_failure: always
    on_start: always
